[package]
name = "jsh"
version = "0.6.0"
authors = ["JinyuanZhou <jinyuanleo@gmail.com>"]
edition = "2024"
rust-version = "1.88"

[dependencies]
bytes = "1.3.0"                                  # helps manage buffers
is_executable = "1.0.6"
nix = { version = "0.31.3", features = ["fs", "process", "signal", "term"] }
rustyline = "18.0.1"
thiserror = "1.0.38"                             # error handling
